version: "3.0"

services:
  lb:
    image: nginx:alpine
    hostname: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/proxy.conf:/etc/nginx/proxy.conf:ro
      ## Capture all server logs at 'logs' directory
      - ./nginx/logs/:/var/log/nginx/
    ports:
      ## Set port forwarding to local port 8080 from nginx port 80
      - 8080:80
    depends_on:
      - app

  app:
    image: mahendrshinde/myweb
    ports:
      - 80
    deploy:
      replicas: 3
